# -*- coding: utf-8 -*-
"""GreyColorSelection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ed1HRYWZAGw92SzJi-JVyYevgeoKLzd3

# Code to perform Color Selection on gray image
Select one perticular color from an image.

Eg. if we want to extract white color. Then extract the pixels that are close to 255.

# Step 1 : Import all the necessary libraries
"""
import streamlit as st
import matplotlib.image as mpimg
import matplotlib.pyplot as plt
import numpy as np
import cv2


st.title("Grey Color Selection")
# Step 2 : Read , Convert and display image


uploaded_file = st.file_uploader("Choose a file")
submit = st.button('Start Convertion')
col1, col2 = st.columns(2)


if uploaded_file is not None:
     # To read file as bytes:
     imageColor = mpimg.imread(uploaded_file)
     col1.header("Original")
     col1.image(imageColor, caption='Original Image')


if submit:
    imageGray = cv2.cvtColor(imageColor , cv2.COLOR_RGB2GRAY)
    plt.imshow(imageGray, cmap = 'gray')
    # imageGray.shape

    # Step 3 : Extract the required pixel from image.
    #Here we will extract color white. pixel value 255


    # making a copy of actual image
    imageCopy = np.copy(imageGray)
    # imageCopy.shape

    #If our pixel is less than 250. Then we make all of them as 0.

    imageCopy[ imageCopy[: , :] < 250 ] = 0
    col2.header("Grayscale")
    col2.image(imageCopy , caption= "grey select")

    # plt.imshow(imageCopy, cmap = 'gray')
    # plt.show()

    cv2.imwrite("/Users/shubhamrathod/PycharmProjects/Black_image_lane_c.jpg",imageCopy)